# Goldberg dataset config

data:
  dataset_path: "data_preprocessing/datasets/goldberg/all_groups.csv"

  hugging_face:
    dataset_name: "Goldberg"
    csv_filename: "all_groups.csv"

tracking:
  project: "gut-microbiome-goldberg"
  tags: ["goldberg", "gridsearch", "unbiased-cv"]
  space_id: "vaibhav2507/gut-microbiome-goldberg-test"