# Tanaka dataset config

data:
  dataset_path: "data_preprocessing/datasets/tanaka/month_2.csv"

  hugging_face:
    dataset_name: "Tanaka"
    csv_filename: "month_2.csv"

tracking:
  project: "gut-microbiome-tanaka"
  tags: ["tanaka", "gridsearch", "unbiased-cv"]
  space_id: "vaibhav2507/gut-microbiome-tanaka-test"